SELECT SUBMISSION_DATE,
      (SELECT COUNT(DISTINCT HACKER_ID)
       FROM SUBMISSIONS AS SUB2
       WHERE SUB2.SUBMISSION_DATE=SUB1.SUBMISSION_DATE
             AND (SELECT COUNT(DISTINCT SUBMISSION_DATE)
                  FROM SUBMISSIONS AS SUB3
                  WHERE SUB3.HACKER_ID=SUB2.HACKER_ID
                        AND SUB3.SUBMISSION_DATE<SUB1.SUBMISSION_DATE)
                            =DATEDIFF(SUB1.SUBMISSION_DATE,'2016-03-01')),

      (SELECT HACKER_ID
       FROM SUBMISSIONS AS SUB4
       WHERE SUB4.SUBMISSION_DATE=SUB1.SUBMISSION_DATE
       GROUP BY HACKER_ID
       ORDER BY COUNT(SUBMISSION_ID) DESC, HACKER_ID LIMIT 1) AS HID,

      (SELECT NAME
       FROM HACKERS
       WHERE HACKER_ID=HID)

FROM (SELECT DISTINCT SUBMISSION_DATE FROM SUBMISSIONS) AS SUB1
